# fly.toml app configuration file generated for omniroute-t1ugsa

app = 'omniroute-t1ugsa'
primary_region = 'sin'

[build]

[deploy]

[env]
  BIND = '0.0.0.0'
  HOST = '0.0.0.0'
  HOSTNAME = '0.0.0.0'
  TZ = 'Asia/Shanghai'

[processes]
  app = 'node run-standalone.mjs'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 20128
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024